version: 2.1
jobs:
  build:
    docker:
      - image: afreeorange/build:latest
    steps:
      - checkout

      - run:
          name: Deploying to public.nikhil.io
          command: aws s3 cp index.html s3://public.nikhil.io/wifi-qrcode-generator/

